#server:
#  port: 8000
#  servlet:
#    context-path: /api/v1
#
#spring:
#  # PostgreSQL Configuration
#  app:
#    name: Produit Management API
#  datasource:
#    url: jdbc:postgresql://localhost:5432/pharma_produit_db
#    username: postgres
#    password: 12345
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 300000
#      pool-name: HikariPool-Produit
#  
#  # JPA Configuration
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        use_sql_comments: true
#        jdbc:
#          batch_size: 20
#          fetch_size: 100
#        order_inserts: true
#        order_updates: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  app:
    name: Produit Management API

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: HikariPool-Produit

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 100
        order_inserts: true
        order_updates: true
